# cmake/ClangdSetup.cmake
# Makes clangd (used by Zed, VS Code, Neovim, etc.) work out of the box by
# symlinking the generated compile_commands.json into the project root after
# configuration. No IDE-specific config files required.

if(NOT CMAKE_EXPORT_COMPILE_COMMANDS)
    set(CMAKE_EXPORT_COMPILE_COMMANDS ON CACHE INTERNAL "")
endif()

set(_safi_ccjson_src "${CMAKE_BINARY_DIR}/compile_commands.json")
set(_safi_ccjson_dst "${CMAKE_SOURCE_DIR}/compile_commands.json")

# Create the symlink at configure-time if the build tree has already produced
# compile_commands.json, and again after every build so renames are picked up.
add_custom_target(safi_clangd_link ALL
    COMMAND ${CMAKE_COMMAND} -E create_symlink
        "${_safi_ccjson_src}" "${_safi_ccjson_dst}"
    COMMENT "Linking compile_commands.json → ${_safi_ccjson_dst}"
    VERBATIM
)

# Emit a .clangd file at the project root if missing. It tells clangd to treat
# headers as C (not C++) so we don't get C++ diagnostics on engine headers.
set(_safi_clangd_file "${CMAKE_SOURCE_DIR}/.clangd")
if(NOT EXISTS "${_safi_clangd_file}")
    file(WRITE "${_safi_clangd_file}"
"# Generated by SafiEngine/cmake/ClangdSetup.cmake
# Treat engine headers as C11; add project-wide flags.
CompileFlags:
  Add: [-std=c11, -Wall, -Wextra, -Wpedantic]
  Compiler: clang

---
If:
  PathMatch: .*\\\\.h$
CompileFlags:
  Add: [-xc]
")
endif()
